version: "3.9"
services:
  frontend:
    image: dev10capstoneteam7images.azurecr.io/capstone-client:v2
    ports:
      - "80:80"
    depends_on:
      - api
      - db
    # this needs to be your web app name
    domainname: "dev10-capstone-team7"
  api:
    image: dev10capstoneteam7images.azurecr.io/capstone-server:v2
    environment:
      DB_URL: jdbc:mysql://db:3306/soundtrack
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
  db:
    image: dev10capstoneteam7images.azurecr.io/capstone-db:v2
