@url = http://localhost:8080/api/location

## Testing find all locations
GET {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvYi5ob2xzZXJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG8iLCJsYXN0TmFtZSI6IkhvbHNlIiwicGhvbmUiOiIxMjMtMTIzLTEyMzQiLCJhY2Nlc3MiOiJST0xFX1VTRVIiLCJhdXRob3JpemF0aW9uIjpbXSwicm9sZXMiOltdLCJleHAiOjE2MTM2NzQxOTh9.BBhDO0xR8HtGeAYTMbHOlzesM7f71qEguRsPJMSdQSE

###

## Testing find location by id
GET {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvLmhvbHNlQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IktlbHRvIiwibGFzdE5hbWUiOiJIb2xzZSIsInBob25lIjoiMTIzLTEyMy0xMjM0IiwiYWNjZXNzIjoiVVNFUiIsImV4cCI6MTYxMzY2OTkwMn0.vsYXt4qxMbwqtFANxGGL1VYxPwy8OBQrEThbOj8Ouko
###

## Testing add a location
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvYi5ob2xzZXJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG9uIiwibGFzdE5hbWUiOiJIb2xzZW4iLCJwaG9uZSI6IjEyMy0xMjMtMTIzNCIsImFjY2VzcyI6IlJPTEVfQURNSU5JU1RSQVRPUiIsImF1dGhvcml6YXRpb24iOltdLCJyb2xlcyI6WyJ0ZWNoIiwiYXYiXSwiZXhwIjoxNjEzNzYzMDI1fQ.TYtOfZMlJcKH3xhdGbbb_JllE30YYP0TxqF4O-ql7Y0

{
    "address": "481 Desnoyer St SE",
    "name": "481"
}

###

## Testing update a location
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "locationId": 1,
    "address": "821 Thornton St SE",
    "name": "Thor"
}

###

## Testing delete a location
DELETE {{url}}/2 HTTP/1.1