@url = http://localhost:8080/api/user


## Testing find all user
GET {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvbi5ob2xzZW5AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG9uIiwibGFzdE5hbWUiOiJIb2xzZW4iLCJwaG9uZSI6IjEyMy0xMjMtMTIzNCIsImFjY2VzcyI6IkFETUlOSVNUUkFUT1IiLCJyb2xlcyI6WyJhdiIsImF2IiwidGVjaCIsInRlY2giXSwiZXhwIjoxNjEzNjcwMDQxfQ.sPpQGCIhBYJ7UPmV0-U1yngKBx7bZGlT0S_9zn9Mc7s
###

## Testing find user by id
GET {{url}}/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvYi5ob2xzZXJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG8iLCJsYXN0TmFtZSI6IkhvbHNlIiwicGhvbmUiOiIxMjMtMTIzLTEyMzQiLCJhY2Nlc3MiOiJST0xFX1VTRVIiLCJhdXRob3JpemF0aW9uIjpbXSwicm9sZXMiOltdLCJleHAiOjE2MTM2NzM5NzV9.nQW_gKNP7pFzRkICUEK98iqwSmXHsUavf0gjkr6uyGI

###

## Testing add a user
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvYi5ob2xzZXJAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG8iLCJsYXN0TmFtZSI6IkhvbHNlIiwicGhvbmUiOiIxMjMtMTIzLTEyMzQiLCJhY2Nlc3MiOiJST0xFX1VTRVIiLCJhdXRob3JpemF0aW9uIjpbXSwicm9sZXMiOltdLCJleHAiOjE2MTM2NzM5NzV9.nQW_gKNP7pFzRkICUEK98iqwSmXHsUavf0gjkr6uyGI

{
    "firstName": "Kelton",
    "lastName": "Holsen",
    "email": "keltob.holser@gmail.com",
    "phone": "123-123-1234",
    "accessLevel": "ROLE_ADMINISTRATOR",
    "password": "keltonholsenholsenkelton",
    "roles": [
        "tech", "av"
    ]
}

###

## Testing update a user
PUT {{url}}/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvbi5ob2xzZW5AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiS2VsdG9uIiwibGFzdE5hbWUiOiJIb2xzZW4iLCJwaG9uZSI6IjEyMy0xMjMtMTIzNCIsImFjY2VzcyI6IkFETUlOSVNUUkFUT1IiLCJyb2xlcyI6WyJhdiIsImF2IiwidGVjaCIsInRlY2giXSwiZXhwIjoxNjEzNjY4ODc2fQ.Eg3RXodkOz0RH6ypOtuw749MWW_crxCXJNpeuXncnkg


{
    "userId": 3,
    "firstName": "AyDy",
    "lastName": "Burling",
    "email": "aydy.burling@gmail.com",
    "phone": "123-456-7890",
    "accessLevel": "USER",
    "password": "passwordpassword",
    "roles": [
        "pom"
    ]
}

###

## Testing delete a user
DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzb3VuZC10cmFjayIsInN1YiI6ImtlbHRvLmhvbHNlQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6IktlbHRvIiwibGFzdE5hbWUiOiJIb2xzZSIsInBob25lIjoiMTIzLTEyMy0xMjM0IiwiYWNjZXNzIjoiVVNFUiIsImV4cCI6MTYxMzY3MDk4Mn0.wMm4w-ECVulClbKJmgLWthfD3dQt9Si8HqggjO32Ef8